### ISSUE TITLE
HChang26 - Risk of Permanently Lost Rewards due to Claiming Before Treasury Deposit

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-11-convergence-judging#110]
HChang26

medium

# Risk of Permanently Lost Rewards due to Claiming Before Treasury Deposit

## Summary
When Treasury Bond `depositMultipleToken()` in current TDE and users try to `claimRewards()` for current TDE, users may lose their rightful rewards.

## Vulnerability Detail
The mechanism responsible for TreasuryBonds depositing rewards into `YsDistributor.sol` through the `depositMultipleToken()` function calculates the TDE for reward distribution based on the current cvgCycle. Each cvgCycle spans a week, and `TDE_DURATION` equals 12 weeks or 12 cvgCycles. This calculation of `_actualTDE` results in two potential outcomes: the current TDE or the subsequent one.
```solidity
        uint256 _actualCycle = cvgControlTower.cvgCycle();
        uint256 _actualTDE = _actualCycle % TDE_DURATION == 0
            ? _actualCycle / TDE_DURATION
            : (_actualCycle / TDE_DURATION) + 1;
```
The issue arises when users use `claimRewards()` for the current TDE before the execution of `depositMultipleToken()` within the same block. If, coincidentally, the TDE calculation lands on the current TDE and `claimRewards()` is executed first, users risk permanently losing their rewards. Once a specific TDE id is claimed, users are unable to make further claims, effectively trapping their rewards within the `YsDistributor.sol` contract.
```solidity
    function claimRewards(uint256 tokenId, uint256 tdeId, address receiver, address operator) external {
        ICvgControlTower _cvgControlTower = cvgControlTower;
        ILockingPositionService _lockingPositionService = lockingPositionService;
        ILockingPositionManager _lockingPositionManager = lockingPositionManager;
        require(_lockingPositionManager.unlockingTimestampPerToken(tokenId) < block.timestamp, "TOKEN_TIMELOCKED");

        if (msg.sender != _cvgControlTower.cvgUtilities()) {
            operator = msg.sender;
        }
        require(
            operator == _lockingPositionManager.ownerOf(tokenId) ||
                operator == lockingPositionDelegate.delegatedYsCvg(tokenId),
            "NOT_OWNED_OR_DELEGATEE"
        );

      ->uint256 cycleClaimed = tdeId * TDE_DURATION;

        require(_lockingPositionService.lockingPositions(tokenId).lastEndCycle >= cycleClaimed, "LOCK_OVER");

      ->require(_cvgControlTower.cvgCycle() >= cycleClaimed, "NOT_AVAILABLE");

      ->require(!rewardsClaimedForToken[tokenId][tdeId], "ALREADY_CLAIMED");

         and the totalSupply of ysCvg at the specified TDE. */
        uint256 share = (_lockingPositionService.balanceOfYsCvgAt(tokenId, cycleClaimed) * 10 ** 20) /
            _lockingPositionService.totalSupplyYsCvgHistories(cycleClaimed);

        require(share != 0, "NO_SHARES");

        _claimTokenRewards(tokenId, tdeId, share, receiver);

        rewardsClaimedForToken[tokenId][tdeId] = true;
    }
```
## Impact
The rewards are essentially locked in the contract if `claimRewards()` is executed before `depositMultipleToken()` in the same block, resulting in users being unable to claim their rightful rewards.

## Code Snippet
https://github.com/sherlock-audit/2023-11-convergence/blob/main/sherlock-cvg/contracts/Rewards/YsDistributor.sol#L101
https://github.com/sherlock-audit/2023-11-convergence/blob/main/sherlock-cvg/contracts/Rewards/YsDistributor.sol#L155
## Tool used

Manual Review

## Recommendation
```solidity
    function claimRewards(uint256 tokenId, uint256 tdeId, address receiver, address operator) external {
        ICvgControlTower _cvgControlTower = cvgControlTower;
        ILockingPositionService _lockingPositionService = lockingPositionService;
        ILockingPositionManager _lockingPositionManager = lockingPositionManager;
        require(_lockingPositionManager.unlockingTimestampPerToken(tokenId) < block.timestamp, "TOKEN_TIMELOCKED");

        if (msg.sender != _cvgControlTower.cvgUtilities()) {
            operator = msg.sender;
        }
        require(
            operator == _lockingPositionManager.ownerOf(tokenId) ||
                operator == lockingPositionDelegate.delegatedYsCvg(tokenId),
            "NOT_OWNED_OR_DELEGATEE"
        );

        uint256 cycleClaimed = tdeId * TDE_DURATION;

        require(_lockingPositionService.lockingPositions(tokenId).lastEndCycle >= cycleClaimed, "LOCK_OVER");

-       require(_cvgControlTower.cvgCycle() >= cycleClaimed, "NOT_AVAILABLE");
+       require(_cvgControlTower.cvgCycle() > cycleClaimed, "NOT_AVAILABLE");

        require(!rewardsClaimedForToken[tokenId][tdeId], "ALREADY_CLAIMED");

         and the totalSupply of ysCvg at the specified TDE. */
        uint256 share = (_lockingPositionService.balanceOfYsCvgAt(tokenId, cycleClaimed) * 10 ** 20) /
            _lockingPositionService.totalSupplyYsCvgHistories(cycleClaimed);

        require(share != 0, "NO_SHARES");

        _claimTokenRewards(tokenId, tdeId, share, receiver);

        rewardsClaimedForToken[tokenId][tdeId] = true;
    }
```

**Comment by IAm0x52** [comment]
Escalate.

This should be low. In the claimRewards function, the user is able to input the exact TDE they wish to claim and only themselves or the trusted operator can claim. I believe it would be user error to claim a TDE cycle before the rewards have been distributed, especially in such a narrow window. The check exists as a user input validation to help prevent users from claiming before they should. If this check did not exist then claiming on an incorrect cycle would be user error. Therefore an example of a user being able to defeat the input validation to harm only themselves should also be user error and a low severity issue.

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> This should be low. In the claimRewards function, the user is able to input the exact TDE they wish to claim and only themselves or the trusted operator can claim. I believe it would be user error to claim a TDE cycle before the rewards have been distributed, especially in such a narrow window. The check exists as a user input validation to help prevent users from claiming before they should. If this check did not exist then claiming on an incorrect cycle would be user error. Therefore an example of a user being able to defeat the input validation to harm only themselves should also be user error and a low severity issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@deadrosesxyz you might want to take a look at this issue.

I am borderline about this one, if its just like @IAm0x52 mentioned that we shouldn't claimed during TDE cycle, then why does the check not reflect it correctly? Imo it is totally possible for users to may well claim during TDE cycle and lose rewards while interacting with the front-end. I think this should remain as medium severity.

**Comment by deadrosesxyz** [comment]
The check is incorrect and can result in permanent loss of funds. Imo medium is appropriate

**Comment by ChechetkinVV** [comment]
> @deadrosesxyz you might want to take a look at this issue.
> 
> I am borderline about this one, if its just like @IAm0x52 mentioned that we shouldn't claimed during TDE cycle, then why does the check not reflect it correctly? Imo it is totally possible for users to may well claim during TDE cycle and lose rewards while interacting with the front-end. I think this should remain as medium severity.

It's impossible to claim during TDE because of the #207 issue.

**Comment by nevillehuang** [comment]
@ChechetkinVV Seems like a valid point. In that case, this issue seems to be invalid.

@shalbe-cvg @walk-on-me @0xR3vert might want to take a look and verify.

**Comment by Czar102** [comment]
Planning to accept the escalation and make this a low severity issue.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-11-convergence-judging/issues/110/#issuecomment-1869990391): accepted

**Comment by IAm0x52** [comment]
Fix looks good. Inequality changed from `>=` to `>`
